# Core scope
sonar.sourceEncoding=UTF-8
sonar.sources=src

# Exclude generated/irrelevant folders from analysis
sonar.exclusions=tests/**,dist/**,coverage/**,docs/**,node_modules/**

# Coverage from Vitest (lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=tests/**,dist/**,docs/**
